[package]
authors = ['ctt']
edition = '2018'
name = 'ctt-pallet-kp'
version = "2.0.0-rc2"
license = "GPL-3.0-only"
homepage = "https://substrate.dev"
repository = "https://github.com/pfcoder/substrate/"
description = "Knowledge power pallet"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-core = { version = "2.0.0-rc2", default-features = false, path = "../../../../primitives/core" }

[dependencies.sp-std]
default-features = false
version = "2.0.0-rc2"
path = "../../../../primitives/std"

[dependencies.frame-support]
default-features = false
version = "2.0.0-rc2"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-rc2"
path = "../../../../frame/system"
[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-rc2"
path = "../../../../primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-rc2"
path = "../../../../primitives/io"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-rc2"
path = "../../../../primitives/runtime"

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'serde'
]
